python_library(
    name = "mylib",
    srcs = ["mylib.py"],
    visibility = [
        "//src/...",
        "//test/...",
    ],
    deps = [
        "//third_party/python:packaging",
        "//third_party/python:distlib",
    ],
)
