python_test(
    name = "lib_test",
    srcs = ["test.py"],
    deps = ["//src/lib:mylib"],
)

python_test(
    name = "cross_compile_test",
    srcs = ["cross_compile_test.py"],
    deps = ["//src/lib:mylib"],
)
